version: 2.1

jobs:
  unit_test:
    machine:
      enabled: true
      image: "ubuntu-1604:201903-01"
    steps:
      - checkout
      - run:
          name: run tests py2
          command: python test/check-skip-env/check_skip_env_test.py
      - run:
          name: run tests py3
          command: python3 test/check-skip-env/check_skip_env_test.py


workflows:
  version: 2
  test:
    jobs:
      - unit_test:
          filters:
            tags:
              only: /^v.*/
